#!/bin/bash
# Script to check if the OGP image URLs for slides match the file structure and are correct

# Exit early
# See: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin
set -e

# Variables
BASE_URL="https://yKicchan.github.io/awesome-marp-template"
SRC_DIR="src"
SLIDE_FILENAME="index.md"
OGP_FILENAME="index.png"
OGP_SET_PREFIX="image:"

# Colors
RED="\x1b[31m"
GREEN="\x1b[32m"
YELLOW="\x1b[33m"
OFF="\x1b[0m"

# Retrieve the paths of specified files
slide_file_paths=$(find "$SRC_DIR" -type f -name "$SLIDE_FILENAME")
if [[ -z "$slide_file_paths" ]]; then
  echo -e "${YELLOW}No slide files found in $SRC_DIR.$OFF"
  exit 0
fi

# Extract lines containing BASE_URL (i.e., lines with OGP settings) from the files
actual_image_urls=$(grep -rh "$BASE_URL" "$SRC_DIR" | sed "s/^$OGP_SET_PREFIX//")
# Generate the expected URLs
expected_image_urls=$(echo "$slide_file_paths" | sed "s|$SRC_DIR|$BASE_URL|;s|$SLIDE_FILENAME|$OGP_FILENAME|")

# Convert to arrays
# shellcheck disable=SC2206
slide_file_paths_arr=($slide_file_paths)
# shellcheck disable=SC2206
actual_image_urls_arr=($actual_image_urls)
# shellcheck disable=SC2206
expected_image_urls_arr=($expected_image_urls)

# Array to record mismatched URLs
mismatched_messages=()

# Compare the expected URLs with the actual URLs for each slide file
for ((i = 0; i < ${#slide_file_paths_arr[@]}; i++)); do
  path=${slide_file_paths_arr[$i]}
  expected=${expected_image_urls_arr[$i]}
  actual=${actual_image_urls_arr[$i]}
  if [[ "$expected" != "$actual" ]]; then
    # Record mismatched URLs
    mismatched_messages+=("File: $path\n${GREEN}- Expected: $expected\n${RED}- Actual: $actual${OFF}")
  fi
done

# If all URLs match, exit normally
if [[ ${#mismatched_messages[@]} -eq 0 ]]; then
  echo -e "${GREEN}All image URLs match the expected values.$OFF"
  exit 0
fi

# If mismatched URLs exist, output an error
echo -e "${RED}The following mismatched image URLs were found:$OFF\n"
for message in "${mismatched_messages[@]}"; do
  echo -e "$message\n"
done
exit 1
