#!/bin/bash
# Script to generate a new slide set from the template
# Also updates the OGP URL settings in the template according to the file structure

# template/ にはパターン集(patterns.md)等も含まれるため index.md のみ複製する
mkdir -p src/$1
cp template/index.md src/$1/index.md

sed -i '' "s|{{PATH}}|$1|" src/$1/index.md
